#!/usr/bin/env python3

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

MARKER_NAME = ".skill-sync-generated"
IGNORE_PATTERNS = shutil.ignore_patterns(".DS_Store", "__pycache__")


def build_parser() -> argparse.ArgumentParser:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(
        description="Sync shared Agent Skills into Claude and Codex runtime directories."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=repo_root / "shared-skills",
        help="Canonical shared skill directory.",
    )
    parser.add_argument(
        "--claude-dir",
        type=Path,
        default=repo_root / ".claude" / "skills",
        help="Claude Code project skill directory.",
    )
    parser.add_argument(
        "--codex-dir",
        type=Path,
        default=repo_root / ".agents" / "skills",
        help="Codex project skill directory.",
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help="Remove previously generated skills that no longer exist in the source directory.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that generated skill directories match the source without writing changes.",
    )
    return parser


def extract_skill_name(skill_dir: Path) -> str:
    skill_file = skill_dir / "SKILL.md"
    if not skill_file.exists():
        raise ValueError(f"Missing SKILL.md in {skill_dir}")

    lines = skill_file.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{skill_file} must start with YAML frontmatter")

    for line in lines[1:]:
        stripped = line.strip()
        if stripped == "---":
            break
        if stripped.startswith("name:"):
            return stripped.split(":", 1)[1].strip()

    raise ValueError(f"Could not find frontmatter name in {skill_file}")


def discover_skills(source_root: Path) -> list[Path]:
    if not source_root.exists():
        return []

    return sorted(
        child for child in source_root.iterdir() if child.is_dir() and (child / "SKILL.md").exists()
    )


def ensure_skill_shape(skill_dir: Path) -> str:
    skill_name = extract_skill_name(skill_dir)
    if skill_name != skill_dir.name:
        raise ValueError(
            f"Skill directory name mismatch: frontmatter name '{skill_name}' != folder '{skill_dir.name}'"
        )
    return skill_name


def overwrite_generated_skill(source_dir: Path, target_dir: Path, repo_root: Path) -> None:
    if target_dir.exists():
        marker = target_dir / MARKER_NAME
        if not marker.exists():
            raise RuntimeError(
                f"Refusing to overwrite non-generated directory: {target_dir}"
            )
        shutil.rmtree(target_dir)

    shutil.copytree(source_dir, target_dir, ignore=IGNORE_PATTERNS)
    (target_dir / MARKER_NAME).write_text(
        marker_text(source_dir, repo_root),
        encoding="utf-8",
    )


def marker_text(source_dir: Path, repo_root: Path) -> str:
    try:
        relative_source = source_dir.resolve().relative_to(repo_root)
    except ValueError:
        relative_source = Path(source_dir.name)
    return f"Generated by scripts/sync-agent-skills.py from {relative_source.as_posix()}\n"


def prune_generated_skills(source_names: set[str], target_root: Path) -> list[Path]:
    removed: list[Path] = []
    if not target_root.exists():
        return removed

    for child in sorted(target_root.iterdir()):
        if not child.is_dir():
            continue
        if not (child / MARKER_NAME).exists():
            continue
        if child.name in source_names:
            continue
        shutil.rmtree(child)
        removed.append(child)
    return removed


def sync_target(
    source_root: Path, target_root: Path, prune: bool, repo_root: Path
) -> tuple[list[Path], list[Path]]:
    target_root.mkdir(parents=True, exist_ok=True)

    skill_dirs = discover_skills(source_root)
    synced: list[Path] = []
    for skill_dir in skill_dirs:
        skill_name = ensure_skill_shape(skill_dir)
        overwrite_generated_skill(skill_dir, target_root / skill_name, repo_root)
        synced.append(target_root / skill_name)

    removed = (
        prune_generated_skills({skill.name for skill in skill_dirs}, target_root)
        if prune
        else []
    )
    return synced, removed


def file_map(root: Path, *, ignore_marker: bool) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for path in sorted(root.rglob("*")):
        if path.is_dir():
            continue
        if path.name == ".DS_Store" or "__pycache__" in path.parts:
            continue
        if ignore_marker and path.name == MARKER_NAME:
            continue
        rel = path.relative_to(root).as_posix()
        files[rel] = path.read_bytes()
    return files


def check_target(source_root: Path, target_root: Path, repo_root: Path) -> list[str]:
    errors: list[str] = []
    source_skills = discover_skills(source_root)
    source_names = {skill.name for skill in source_skills}

    for source_dir in source_skills:
        target_dir = target_root / source_dir.name
        if not target_dir.exists():
            errors.append(f"missing generated skill: {target_dir}")
            continue
        marker = target_dir / MARKER_NAME
        if not marker.exists():
            errors.append(f"missing generated marker: {marker}")
            continue
        expected_marker = marker_text(source_dir, repo_root)
        actual_marker = marker.read_text(encoding="utf-8")
        if actual_marker != expected_marker:
            errors.append(f"stale generated marker: {marker}")

        source_files = file_map(source_dir, ignore_marker=False)
        target_files = file_map(target_dir, ignore_marker=True)
        source_paths = set(source_files)
        target_paths = set(target_files)

        for rel in sorted(source_paths - target_paths):
            errors.append(f"missing file in {target_dir}: {rel}")
        for rel in sorted(target_paths - source_paths):
            errors.append(f"extra file in {target_dir}: {rel}")
        for rel in sorted(source_paths & target_paths):
            if source_files[rel] != target_files[rel]:
                errors.append(f"drifted file in {target_dir}: {rel}")

    if target_root.exists():
        for child in sorted(target_root.iterdir()):
            if not child.is_dir():
                continue
            if child.name in source_names:
                continue
            if (child / MARKER_NAME).exists():
                errors.append(f"generated skill no longer in source: {child}")
            elif (child / "SKILL.md").exists():
                errors.append(f"unmanaged runtime skill not in source: {child}")

    return errors


def main() -> int:
    args = build_parser().parse_args()
    source_root = args.source.resolve()
    repo_root = Path(__file__).resolve().parent.parent
    target_roots = [args.claude_dir.resolve(), args.codex_dir.resolve()]

    if not source_root.exists():
        print(f"Source directory does not exist: {source_root}", file=sys.stderr)
        return 1

    skill_dirs = discover_skills(source_root)
    if not skill_dirs:
        print(f"No skills found in {source_root}")
        return 0

    for skill_dir in skill_dirs:
        ensure_skill_shape(skill_dir)

    if args.check:
        all_errors: list[str] = []
        for target_root in target_roots:
            errors = check_target(source_root, target_root, repo_root)
            if errors:
                all_errors.append(f"[check] {target_root}")
                all_errors.extend(f"  - {error}" for error in errors)
            else:
                print(f"[check] {target_root} OK")
        if all_errors:
            print("Agent skill sync check failed:", file=sys.stderr)
            print("\n".join(all_errors), file=sys.stderr)
            print(
                "Run `python3 scripts/sync-agent-skills.py --prune` to regenerate generated skills.",
                file=sys.stderr,
            )
            return 1
        return 0

    for target_root in target_roots:
        synced, removed = sync_target(source_root, target_root, args.prune, repo_root)
        print(f"[sync] {target_root}")
        for path in synced:
            print(f"  + {path.name}")
        for path in removed:
            print(f"  - {path.name}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
